### ISSUE TITLE
Style speaker announcement blog post

### ISSUE THREAD

**Issue by Kriesse** [cssconf/blog-content#8]
preview here:
http://blog.cssconf.eu/2017/02/22/first-speaker-announcement-cssconf-eu-2017/?preview

- [x] add picture
- [ ] proofread
- [ ] add links to speaker detail pages
- [ ] any visual improvement (better layouting of the image? nicer headlines? ping @RalloTubbs @silkine)

**Comment by Lucie-H** [comment]
@lukaszklis i just realised the sub-headline should probably also show the same order of people like in the text, starting with Ivana.

**Comment by Kriesse** [comment]
@Lucie-H ah good catch! will update right now.

**Comment by silkine** [comment]
I'm not completely sure about how to improve here? The image could use doubled size, since it doesn't seem retina ready. But other than that it seems ok for me and on style. The headlines - I don't know enough about the consistent styleguide, but I think the Font looks much better using lowercase letters instead of all of it uppercase. As I see it, the big size contrast between the uppercase letters and lowercase letters, is what makes the Walsheim font so special.

**Comment by lukaszklis** [comment]
^ wrong reference, sorry!

**Comment by lukaszklis** [comment]
Do we still need this PR?

**Comment by Kriesse** [comment]
@lukaszklis nope, let's close it
